In [15]:
#With function

In [12]:
import nltk
from nltk.util import ngrams
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [14]:
from nltk.translate.phrase_based import extract
def extract_ngrams(data,num):
  n_grams=ngrams(nltk.word_tokenize(data),num)
  return[' '.join(grams) for grams in n_grams]

data ='A class is a  blueprint for the object in a programming language.'

print("1-gram: ",extract_ngrams(data,1))
print("2-gram: ",extract_ngrams(data,2))
print("3-gram: ",extract_ngrams(data,3))
print("4-gram: ",extract_ngrams(data,4))


print("5-gram: ",extract_ngrams(data,5))
print("6-gram: ",extract_ngrams(data,6))

1-gram:  ['A', 'class', 'is', 'a', 'blueprint', 'for', 'the', 'object', 'in', 'a', 'programming', 'language', '.']
2-gram:  ['A class', 'class is', 'is a', 'a blueprint', 'blueprint for', 'for the', 'the object', 'object in', 'in a', 'a programming', 'programming language', 'language .']
3-gram:  ['A class is', 'class is a', 'is a blueprint', 'a blueprint for', 'blueprint for the', 'for the object', 'the object in', 'object in a', 'in a programming', 'a programming language', 'programming language .']
4-gram:  ['A class is a', 'class is a blueprint', 'is a blueprint for', 'a blueprint for the', 'blueprint for the object', 'for the object in', 'the object in a', 'object in a programming', 'in a programming language', 'a programming language .']
5-gram:  ['A class is a blueprint', 'class is a blueprint for', 'is a blueprint for the', 'a blueprint for the object', 'blueprint for the object in', 'for the object in a', 'the object in a programming', 'object in a programming language', 'in a

In [16]:
#without function

In [23]:
sentence=input('Enter the sentences:')
n=int(input('enter the number of ngrams:'))

token=nltk.word_tokenize(sentence)

ngrams=ngrams(token,n)

for grams in ngrams:
  print(grams)

Enter the sentences:i am shivani 
enter the number of ngrams:3
('i', 'am', 'shivani')


In [52]:
#one hot encoding vector form
import numpy as np

In [45]:
text ={'A class is a  blueprint ,for the object in a programming language.'}
token_index = {}

counter=0

for sample in text:
  for considered_word in sample.split():
    if considered_word not in token_index:
      
    
      token_index.update({considered_word : counter + 1}) 
      
      counter = counter + 1    
print(token_index)     

{'A': 1, 'class': 2, 'is': 3, 'a': 4, 'blueprint': 5, ',for': 6, 'the': 7, 'object': 8, 'in': 9, 'programming': 10, 'language.': 11}


In [46]:
max_length = 11

results  = np.zeros(shape = (len(text),
                            max_length,
                            max(token_index.values()) + 1))  

In [50]:
for i, sample in enumerate(text): 
  
  # tokens=nltk.word_tokenize(text)
  for j, considered_word in list(enumerate(token)):
    
    index = token_index.get(considered_word)

results[i,j,index]=1

In [51]:
print(results)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [53]:
#if we suppose to compare the text then we will use one hot encoding.

In [55]:
#u mayuse indices or one hot encoding for checking similary of a text gyan mitttal.org exampls one .
#https://medium.com/analytics-vidhya/one-hot-encoding-of-text-data-in-natural-language-processing-2242fefb2148
#https://gyan-mittal.com/nlp-ai-ml/nlp-word-encoding-by-one-hot-encoding/


**Bag of words (BoW) model in NLP**







In [80]:
#ag of Words model is used to preprocess the text by converting it 
#into a bag of words, which keeps a count of the total occurrences of most frequently used words
# removing punction

In [57]:
import numpy as np
import re


In [87]:
 text ='A class is a \ blueprint ,for the object in a programming language.'
 dataset = nltk.sent_tokenize(text)
  
for i in range(len(dataset)):
    dataset[i] = dataset[i].lower()
    dataset[i] = re.sub(r'\W', ' ',dataset[i])
    dataset[i] = re.sub(r'\s+', ' ', dataset[i])


In [88]:
print(dataset)

['a class is a blueprint for the object in a programming language ']


In [66]:
import re
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
sentences = word_tokenize("I love to learn NLP \n 'a :(")
#for i in range(len(sentences)):
sentences = [word.lower() for word in sentences if re.match('^[a-zA-Z]+', word)]  
sentences

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['i', 'love', 'to', 'learn', 'nlp', 'a']

In [73]:
# Creating the Bag of Words model
word2count = {}
for data in dataset:
	words = nltk.word_tokenize(data)
	for word in words:
		if word not in word2count.keys():
			word2count[word] = 1
		else:
			word2count[word] += 1


In [74]:
print(word2count)

{'a': 3, 'class': 1, 'is': 1, 'blueprint': 1, 'for': 1, 'the': 1, 'object': 1, 'in': 1, 'programming': 1, 'language': 1}


In [77]:
import heapq
freq_words = heapq.nlargest(100, word2count, key=word2count.get)

In [78]:
print(freq_words)

['a', 'class', 'is', 'blueprint', 'for', 'the', 'object', 'in', 'programming', 'language']


In [76]:
X = []
for data in dataset:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(data):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)
X = np.asarray(X)

In [79]:
print(X)

[[1 1 1 1 1 1 1 1 1 1]]
